//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид погаш кр.
    /// </summary>
    // *** Start programmer edit section *** (ВидПогашКр CustomAttributes)

    // *** End programmer edit section *** (ВидПогашКр CustomAttributes)
    public enum ВидПогашКр
    {
        
        // *** Start programmer edit section *** (ВидПогашКр.АннуитПл CustomAttributes)

        // *** End programmer edit section *** (ВидПогашКр.АннуитПл CustomAttributes)
        АннуитПл,
        
        // *** Start programmer edit section *** (ВидПогашКр.ДиффПл CustomAttributes)

        // *** End programmer edit section *** (ВидПогашКр.ДиффПл CustomAttributes)
        ДиффПл,
        
        // *** Start programmer edit section *** (ВидПогашКр.ПлРавДол CustomAttributes)

        // *** End programmer edit section *** (ВидПогашКр.ПлРавДол CustomAttributes)
        ПлРавДол,
    }
}
