//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Клиенты CustomAttributes)

    // *** End programmer edit section *** (Клиенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентыE", new string[] {
            "ФИОКлиента as \'Ф и о клиента\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "Телефон as \'Телефон\'",
            "МестоРаботы as \'Место работы\'",
            "ЮрАдрес as \'Юр адрес\'",
            "ФактАдрес as \'Факт адрес\'",
            "СтажРаботы as \'Стаж работы\'",
            "НомКрДог as \'Ном кр дог\'",
            "РасчСчет as \'Расч счет\'"})]
    [View("КлиентыL", new string[] {
            "ФИОКлиента as \'Ф и о клиента\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "Телефон as \'Телефон\'",
            "МестоРаботы as \'Место работы\'",
            "ЮрАдрес as \'Юр адрес\'",
            "ФактАдрес as \'Факт адрес\'",
            "СтажРаботы as \'Стаж работы\'",
            "НомКрДог as \'Ном кр дог\'",
            "РасчСчет as \'Расч счет\'"})]
    public class Клиенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИОКлиента;
        
        private int fИНН;
        
        private int fКПП;
        
        private int fТелефон;
        
        private string fМестоРаботы;
        
        private string fЮрАдрес;
        
        private string fФактАдрес;
        
        private int fСтажРаботы;
        
        private int fНомКрДог;
        
        private int fРасчСчет;
        
        // *** Start programmer edit section *** (Клиенты CustomMembers)

        // *** End programmer edit section *** (Клиенты CustomMembers)

        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ИНН CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ИНН Get start)

                // *** End programmer edit section *** (Клиенты.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Клиенты.ИНН Get end)

                // *** End programmer edit section *** (Клиенты.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ИНН Set start)

                // *** End programmer edit section *** (Клиенты.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Клиенты.ИНН Set end)

                // *** End programmer edit section *** (Клиенты.ИНН Set end)
            }
        }
        
        /// <summary>
        /// КПП.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.КПП CustomAttributes)

        // *** End programmer edit section *** (Клиенты.КПП CustomAttributes)
        public virtual int КПП
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.КПП Get start)

                // *** End programmer edit section *** (Клиенты.КПП Get start)
                int result = this.fКПП;
                // *** Start programmer edit section *** (Клиенты.КПП Get end)

                // *** End programmer edit section *** (Клиенты.КПП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.КПП Set start)

                // *** End programmer edit section *** (Клиенты.КПП Set start)
                this.fКПП = value;
                // *** Start programmer edit section *** (Клиенты.КПП Set end)

                // *** End programmer edit section *** (Клиенты.КПП Set end)
            }
        }
        
        /// <summary>
        /// МестоРаботы.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.МестоРаботы CustomAttributes)

        // *** End programmer edit section *** (Клиенты.МестоРаботы CustomAttributes)
        [StrLen(255)]
        public virtual string МестоРаботы
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.МестоРаботы Get start)

                // *** End programmer edit section *** (Клиенты.МестоРаботы Get start)
                string result = this.fМестоРаботы;
                // *** Start programmer edit section *** (Клиенты.МестоРаботы Get end)

                // *** End programmer edit section *** (Клиенты.МестоРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.МестоРаботы Set start)

                // *** End programmer edit section *** (Клиенты.МестоРаботы Set start)
                this.fМестоРаботы = value;
                // *** Start programmer edit section *** (Клиенты.МестоРаботы Set end)

                // *** End programmer edit section *** (Клиенты.МестоРаботы Set end)
            }
        }
        
        /// <summary>
        /// НомКрДог.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.НомКрДог CustomAttributes)

        // *** End programmer edit section *** (Клиенты.НомКрДог CustomAttributes)
        public virtual int НомКрДог
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.НомКрДог Get start)

                // *** End programmer edit section *** (Клиенты.НомКрДог Get start)
                int result = this.fНомКрДог;
                // *** Start programmer edit section *** (Клиенты.НомКрДог Get end)

                // *** End programmer edit section *** (Клиенты.НомКрДог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.НомКрДог Set start)

                // *** End programmer edit section *** (Клиенты.НомКрДог Set start)
                this.fНомКрДог = value;
                // *** Start programmer edit section *** (Клиенты.НомКрДог Set end)

                // *** End programmer edit section *** (Клиенты.НомКрДог Set end)
            }
        }
        
        /// <summary>
        /// РасчСчет.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.РасчСчет CustomAttributes)

        // *** End programmer edit section *** (Клиенты.РасчСчет CustomAttributes)
        public virtual int РасчСчет
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.РасчСчет Get start)

                // *** End programmer edit section *** (Клиенты.РасчСчет Get start)
                int result = this.fРасчСчет;
                // *** Start programmer edit section *** (Клиенты.РасчСчет Get end)

                // *** End programmer edit section *** (Клиенты.РасчСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.РасчСчет Set start)

                // *** End programmer edit section *** (Клиенты.РасчСчет Set start)
                this.fРасчСчет = value;
                // *** Start programmer edit section *** (Клиенты.РасчСчет Set end)

                // *** End programmer edit section *** (Клиенты.РасчСчет Set end)
            }
        }
        
        /// <summary>
        /// СтажРаботы.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.СтажРаботы CustomAttributes)

        // *** End programmer edit section *** (Клиенты.СтажРаботы CustomAttributes)
        public virtual int СтажРаботы
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.СтажРаботы Get start)

                // *** End programmer edit section *** (Клиенты.СтажРаботы Get start)
                int result = this.fСтажРаботы;
                // *** Start programmer edit section *** (Клиенты.СтажРаботы Get end)

                // *** End programmer edit section *** (Клиенты.СтажРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.СтажРаботы Set start)

                // *** End programmer edit section *** (Клиенты.СтажРаботы Set start)
                this.fСтажРаботы = value;
                // *** Start programmer edit section *** (Клиенты.СтажРаботы Set end)

                // *** End programmer edit section *** (Клиенты.СтажРаботы Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Телефон CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Get start)

                // *** End programmer edit section *** (Клиенты.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Клиенты.Телефон Get end)

                // *** End programmer edit section *** (Клиенты.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Set start)

                // *** End programmer edit section *** (Клиенты.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Клиенты.Телефон Set end)

                // *** End programmer edit section *** (Клиенты.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФактАдрес.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ФактАдрес CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ФактАдрес CustomAttributes)
        [StrLen(255)]
        public virtual string ФактАдрес
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ФактАдрес Get start)

                // *** End programmer edit section *** (Клиенты.ФактАдрес Get start)
                string result = this.fФактАдрес;
                // *** Start programmer edit section *** (Клиенты.ФактАдрес Get end)

                // *** End programmer edit section *** (Клиенты.ФактАдрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ФактАдрес Set start)

                // *** End programmer edit section *** (Клиенты.ФактАдрес Set start)
                this.fФактАдрес = value;
                // *** Start programmer edit section *** (Клиенты.ФактАдрес Set end)

                // *** End programmer edit section *** (Клиенты.ФактАдрес Set end)
            }
        }
        
        /// <summary>
        /// ФИОКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ФИОКлиента CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ФИОКлиента CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ФИОКлиента Get start)

                // *** End programmer edit section *** (Клиенты.ФИОКлиента Get start)
                string result = this.fФИОКлиента;
                // *** Start programmer edit section *** (Клиенты.ФИОКлиента Get end)

                // *** End programmer edit section *** (Клиенты.ФИОКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ФИОКлиента Set start)

                // *** End programmer edit section *** (Клиенты.ФИОКлиента Set start)
                this.fФИОКлиента = value;
                // *** Start programmer edit section *** (Клиенты.ФИОКлиента Set end)

                // *** End programmer edit section *** (Клиенты.ФИОКлиента Set end)
            }
        }
        
        /// <summary>
        /// ЮрАдрес.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ЮрАдрес CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ЮрАдрес CustomAttributes)
        [StrLen(255)]
        public virtual string ЮрАдрес
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ЮрАдрес Get start)

                // *** End programmer edit section *** (Клиенты.ЮрАдрес Get start)
                string result = this.fЮрАдрес;
                // *** Start programmer edit section *** (Клиенты.ЮрАдрес Get end)

                // *** End programmer edit section *** (Клиенты.ЮрАдрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ЮрАдрес Set start)

                // *** End programmer edit section *** (Клиенты.ЮрАдрес Set start)
                this.fЮрАдрес = value;
                // *** Start programmer edit section *** (Клиенты.ЮрАдрес Set end)

                // *** End programmer edit section *** (Клиенты.ЮрАдрес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыE", typeof(IIS.Otdel2.Клиенты));
                }
            }
            
            /// <summary>
            /// "КлиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыL", typeof(IIS.Otdel2.Клиенты));
                }
            }
        }
    }
}
