//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отдел кр.
    /// </summary>
    // *** Start programmer edit section *** (ОтделКр CustomAttributes)

    // *** End programmer edit section *** (ОтделКр CustomAttributes)
    [AutoAltered()]
    [Caption("Отдел кр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтделКрE", new string[] {
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ОтделКрE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОтделКрL", new string[] {
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class ОтделКр : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Otdel2.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ОтделКр CustomMembers)

        // *** End programmer edit section *** (ОтделКр CustomMembers)

        
        /// <summary>
        /// Отдел кр.
        /// </summary>
        // *** Start programmer edit section *** (ОтделКр.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтделКр.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Otdel2.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтделКр.Сотрудники Get start)

                // *** End programmer edit section *** (ОтделКр.Сотрудники Get start)
                IIS.Otdel2.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтделКр.Сотрудники Get end)

                // *** End programmer edit section *** (ОтделКр.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтделКр.Сотрудники Set start)

                // *** End programmer edit section *** (ОтделКр.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтделКр.Сотрудники Set end)

                // *** End programmer edit section *** (ОтделКр.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтделКрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделКрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделКрE", typeof(IIS.Otdel2.ОтделКр));
                }
            }
            
            /// <summary>
            /// "ОтделКрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделКрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделКрL", typeof(IIS.Otdel2.ОтделКр));
                }
            }
        }
    }
}
