//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Погаш кр.
    /// </summary>
    // *** Start programmer edit section *** (ПогашКр CustomAttributes)

    // *** End programmer edit section *** (ПогашКр CustomAttributes)
    [AutoAltered()]
    [Caption("Погаш кр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПогашКрE", new string[] {
            "Дата as \'Дата\'",
            "ВидПогашКр as \'Вид погаш кр\'",
            "СуммаПогашКр as \'Сумма погаш кр\'",
            "ЗаклКрДог as \'Закл кр дог\'",
            "ЗаклКрДог.ЦельКр as \'Цель кр\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.ФИОКлиента as \'Ф и о клиента\'"}, Hidden=new string[] {
            "ЗаклКрДог.ЦельКр",
            "Организация.Наименование",
            "Клиенты.ФИОКлиента"})]
    [MasterViewDefineAttribute("ПогашКрE", "ЗаклКрДог", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ЦельКр")]
    [MasterViewDefineAttribute("ПогашКрE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ПогашКрE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОКлиента")]
    [View("ПогашКрL", new string[] {
            "Дата as \'Дата\'",
            "Организация.Наименование as \'Наименование\'",
            "Клиенты.ФИОКлиента as \'Ф и о клиента\'",
            "ВидПогашКр as \'Вид погаш кр\'",
            "СуммаПогашКр as \'Сумма погаш кр\'",
            "ЗаклКрДог.НомерКрДог"})]
    public class ПогашКр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Otdel2.ВидПогашКр fВидПогашКр;
        
        private int fСуммаПогашКр;
        
        private IIS.Otdel2.ЗаклКрДог fЗаклКрДог;
        
        private IIS.Otdel2.Организация fОрганизация;
        
        private IIS.Otdel2.Клиенты fКлиенты;
        
        // *** Start programmer edit section *** (ПогашКр CustomMembers)

        // *** End programmer edit section *** (ПогашКр CustomMembers)

        
        /// <summary>
        /// ВидПогашКр.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.ВидПогашКр CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.ВидПогашКр CustomAttributes)
        public virtual IIS.Otdel2.ВидПогашКр ВидПогашКр
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.ВидПогашКр Get start)

                // *** End programmer edit section *** (ПогашКр.ВидПогашКр Get start)
                IIS.Otdel2.ВидПогашКр result = this.fВидПогашКр;
                // *** Start programmer edit section *** (ПогашКр.ВидПогашКр Get end)

                // *** End programmer edit section *** (ПогашКр.ВидПогашКр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.ВидПогашКр Set start)

                // *** End programmer edit section *** (ПогашКр.ВидПогашКр Set start)
                this.fВидПогашКр = value;
                // *** Start programmer edit section *** (ПогашКр.ВидПогашКр Set end)

                // *** End programmer edit section *** (ПогашКр.ВидПогашКр Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.Дата CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.Дата Get start)

                // *** End programmer edit section *** (ПогашКр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПогашКр.Дата Get end)

                // *** End programmer edit section *** (ПогашКр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.Дата Set start)

                // *** End programmer edit section *** (ПогашКр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПогашКр.Дата Set end)

                // *** End programmer edit section *** (ПогашКр.Дата Set end)
            }
        }
        
        /// <summary>
        /// СуммаПогашКр.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.СуммаПогашКр CustomAttributes)
        public virtual int СуммаПогашКр
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр Get start)

                // *** End programmer edit section *** (ПогашКр.СуммаПогашКр Get start)
                int result = this.fСуммаПогашКр;
                // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр Get end)

                // *** End programmer edit section *** (ПогашКр.СуммаПогашКр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр Set start)

                // *** End programmer edit section *** (ПогашКр.СуммаПогашКр Set start)
                this.fСуммаПогашКр = value;
                // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр Set end)

                // *** End programmer edit section *** (ПогашКр.СуммаПогашКр Set end)
            }
        }
        
        /// <summary>
        /// Погаш кр.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.ЗаклКрДог CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаклКрДог"})]
        [NotNull()]
        public virtual IIS.Otdel2.ЗаклКрДог ЗаклКрДог
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог Get start)

                // *** End programmer edit section *** (ПогашКр.ЗаклКрДог Get start)
                IIS.Otdel2.ЗаклКрДог result = this.fЗаклКрДог;
                // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог Get end)

                // *** End programmer edit section *** (ПогашКр.ЗаклКрДог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог Set start)

                // *** End programmer edit section *** (ПогашКр.ЗаклКрДог Set start)
                this.fЗаклКрДог = value;
                // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог Set end)

                // *** End programmer edit section *** (ПогашКр.ЗаклКрДог Set end)
            }
        }
        
        /// <summary>
        /// Погаш кр.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Otdel2.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.Клиенты Get start)

                // *** End programmer edit section *** (ПогашКр.Клиенты Get start)
                IIS.Otdel2.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ПогашКр.Клиенты Get end)

                // *** End programmer edit section *** (ПогашКр.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.Клиенты Set start)

                // *** End programmer edit section *** (ПогашКр.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ПогашКр.Клиенты Set end)

                // *** End programmer edit section *** (ПогашКр.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Погаш кр.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.Организация CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Otdel2.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.Организация Get start)

                // *** End programmer edit section *** (ПогашКр.Организация Get start)
                IIS.Otdel2.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ПогашКр.Организация Get end)

                // *** End programmer edit section *** (ПогашКр.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.Организация Set start)

                // *** End programmer edit section *** (ПогашКр.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ПогашКр.Организация Set end)

                // *** End programmer edit section *** (ПогашКр.Организация Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПогашКрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПогашКрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПогашКрE", typeof(IIS.Otdel2.ПогашКр));
                }
            }
            
            /// <summary>
            /// "ПогашКрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПогашКрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПогашКрL", typeof(IIS.Otdel2.ПогашКр));
                }
            }
        }
    }
}
