//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверка кр кл.
    /// </summary>
    // *** Start programmer edit section *** (ПроверкаКрКл CustomAttributes)

    // *** End programmer edit section *** (ПроверкаКрКл CustomAttributes)
    [AutoAltered()]
    [Caption("Проверка кр кл")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроверкаКрКлE", new string[] {
            "Дата as \'Дата\'",
            "ДоходыВМес as \'Доходы в мес\'",
            "СуммаЕжКр as \'Сумма еж кр\'",
            "НаличЗал as \'Налич зал\'",
            "НаличПоруч as \'Налич поруч\'",
            "Одобрение as \'Одобрение\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "ЗаклКрДог as \'Закл кр дог\'",
            "ЗаклКрДог.ЦельКр as \'Цель кр\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.ФИОКлиента as \'Ф и о клиента\'"}, Hidden=new string[] {
            "Организация.Наименование",
            "ЗаклКрДог.ЦельКр",
            "Клиенты.ФИОКлиента"})]
    [MasterViewDefineAttribute("ПроверкаКрКлE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ПроверкаКрКлE", "ЗаклКрДог", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ЦельКр")]
    [MasterViewDefineAttribute("ПроверкаКрКлE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОКлиента")]
    [View("ПроверкаКрКлL", new string[] {
            "Дата as \'Дата\'",
            "Организация.Наименование as \'Наименование\'",
            "Клиенты.ФИОКлиента as \'Ф и о клиента\'",
            "ЗаклКрДог.СуммаКредита",
            "ДоходыВМес as \'Доходы в мес\'",
            "СуммаЕжКр as \'Сумма еж кр\'",
            "НаличЗал as \'Налич зал\'",
            "НаличПоруч as \'Налич поруч\'",
            "Одобрение as \'Одобрение\'"})]
    public class ПроверкаКрКл : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fДоходыВМес;
        
        private int fСуммаЕжКр;
        
        private bool fНаличЗал;
        
        private bool fНаличПоруч;
        
        private bool fОдобрение;
        
        private IIS.Otdel2.Организация fОрганизация;
        
        private IIS.Otdel2.ЗаклКрДог fЗаклКрДог;
        
        private IIS.Otdel2.Клиенты fКлиенты;
        
        // *** Start programmer edit section *** (ПроверкаКрКл CustomMembers)

        // *** End programmer edit section *** (ПроверкаКрКл CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.Дата CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Дата Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПроверкаКрКл.Дата Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Дата Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.Дата Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.Дата Set end)
            }
        }
        
        /// <summary>
        /// ДоходыВМес.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес CustomAttributes)
        public virtual int ДоходыВМес
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес Get start)
                int result = this.fДоходыВМес;
                // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес Set start)
                this.fДоходыВМес = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес Set end)
            }
        }
        
        /// <summary>
        /// НаличЗал.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗал CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.НаличЗал CustomAttributes)
        public virtual bool НаличЗал
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗал Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличЗал Get start)
                bool result = this.fНаличЗал;
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗал Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличЗал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗал Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличЗал Set start)
                this.fНаличЗал = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗал Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличЗал Set end)
            }
        }
        
        /// <summary>
        /// НаличПоруч.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.НаличПоруч CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.НаличПоруч CustomAttributes)
        public virtual bool НаличПоруч
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличПоруч Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличПоруч Get start)
                bool result = this.fНаличПоруч;
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличПоруч Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличПоруч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличПоруч Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличПоруч Set start)
                this.fНаличПоруч = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличПоруч Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличПоруч Set end)
            }
        }
        
        /// <summary>
        /// Одобрение.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.Одобрение CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.Одобрение CustomAttributes)
        public virtual bool Одобрение
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Одобрение Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.Одобрение Get start)
                bool result = this.fОдобрение;
                // *** Start programmer edit section *** (ПроверкаКрКл.Одобрение Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.Одобрение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Одобрение Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.Одобрение Set start)
                this.fОдобрение = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.Одобрение Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.Одобрение Set end)
            }
        }
        
        /// <summary>
        /// СуммаЕжКр.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжКр CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжКр CustomAttributes)
        public virtual int СуммаЕжКр
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжКр Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжКр Get start)
                int result = this.fСуммаЕжКр;
                // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжКр Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжКр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжКр Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжКр Set start)
                this.fСуммаЕжКр = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжКр Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжКр Set end)
            }
        }
        
        /// <summary>
        /// Проверка кр кл.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаклКрДог"})]
        [NotNull()]
        public virtual IIS.Otdel2.ЗаклКрДог ЗаклКрДог
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Get start)
                IIS.Otdel2.ЗаклКрДог result = this.fЗаклКрДог;
                // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Set start)
                this.fЗаклКрДог = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Set end)
            }
        }
        
        /// <summary>
        /// Проверка кр кл.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Otdel2.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Клиенты Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.Клиенты Get start)
                IIS.Otdel2.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ПроверкаКрКл.Клиенты Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Клиенты Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.Клиенты Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Проверка кр кл.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.Организация CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Otdel2.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Организация Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.Организация Get start)
                IIS.Otdel2.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ПроверкаКрКл.Организация Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Организация Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.Организация Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.Организация Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроверкаКрКлE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаКрКлE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаКрКлE", typeof(IIS.Otdel2.ПроверкаКрКл));
                }
            }
            
            /// <summary>
            /// "ПроверкаКрКлL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаКрКлL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаКрКлL", typeof(IIS.Otdel2.ПроверкаКрКл));
                }
            }
        }
    }
}
